import source.preprocessing.steps as steps

STEP_CLASS_MAPPING = {
    "Adaptive Thresholding": steps.AdaptiveThresholder,
    "Adaptive Histogram Equalizer": steps.AdaptiveHistogramEqualizer,
    "Average Blur Filter": steps.AverageBlurFilter,
    "Bilateral Filter": steps.BilateralFilter,
    "Binary Thresholding": steps.BinaryThresholder,
    "Clipper": steps.Clipper,
    "Dilate Erode Sequencer": steps.DilateErodeSequencer,
    "Dilation Filter": steps.DilationFilter,
    "Dummy Step": steps.DummyStep,
    "Erosion Filter": steps.ErosionFilter,
    "Gaussian Blur Filter": steps.GaussianBlurFilter,
    "Gaussian Noise Injector": steps.GaussianNoiseInjector,
    "Global Histogram Equalizer": steps.GlobalHistogramEqualizer,
    "Grayscale To RGB": steps.GrayscaleToRGB,
    "Local Contrast Normalizer": steps.LocalContrastNormalizer,
    "Mean Normalizer": steps.MeanNormalizer,
    "Median Blur Filter": steps.MedianBlurFilter,
    "Min Max Normalizer": steps.MinMaxNormalizer,
    "Mirrorer": steps.Mirrorer,
    "Non Local Mean Denoiser": steps.NLMeanDenoiser,
    "Otsu Thresholding": steps.OstuThresholder,
    "RGB To Grayscale": steps.RGBToGrayscale,
    "Random Color Jitterer": steps.RandomColorJitterer,
    "Random Cropper": steps.RandomCropper,
    "Random Elastic Transformer": steps.RandomElasticTransformer,
    "Random Flipper": steps.RandomFlipper,
    "Random Perspective Transformer": steps.RandomPerspectiveTransformer,
    "Random Rotator": steps.RandomRotator,
    "Random Sharpening": steps.RandomSharpening,
    "Reverse Scaler": steps.ReverseScaler,
    "Rotator": steps.Rotator,
    "Shape Resizer": steps.ShapeResizer,
    "Square Shape Padder": steps.SquareShapePadder,
    "Standard Normalizer": steps.StandardNormalizer,
    "Threshold to Zero": steps.ZeroThreshold,
    "Truncated Thresholding": steps.TruncatedThresholder,
    "Type Caster": steps.TypeCaster,
}
